### ISSUE TITLE
Kanban board review

### ISSUE THREAD

**Issue by ShahierNashaat** [ShahierNashaat/javascript-capstone#21]
https://github.com/ShahierNashaat/javascript-capstone/projects/1

2 team members

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ShahierNashaat** [comment]
Thank you for your review.
